osi.constant('appConstants',{
			   tab1 : "tab1",
			   tab2 : "tab2",
			   tab3 : "tab3",
			   tab4 : "tab4",
			   tab5 : "tab5",
			   tab6 : "tab6",
			   tab7 : "tab7",
			   tab8 : "tab8",
			   tab9 : "tab9",
               personalInfo: "Personal Info",
			   userResponsibility: "User Responsibilty",
			   functionExclusion: "Function Exclusion",
			   operationExclusion: "Operation Exclusion",
			   inventoryOrg: "Inventory Organization Assignment",
			   rolesAndDept: "Roles and Department",
			   categoryApproverForPR: "Purchase Requisition",
			   categoryApproverForPO: "Purchase Order",
			   categoryApproverForMR: "Material Requisition",
			   exceptionMessage: "Critical Server Issue, Please Contact Administrator",
			   endDate: "12-31-2100",
			   selectedTabClass:"selectedInfoTab"
		   });
